### PR TITLE
fixed an issue in checking https

### PR DESCRIPTION
**Pull request by TheM4hd1**
replaced .contains("https") with .hasPrefix("https")
.contains can cause a problem.

### CODE REVIEW

**Comment by ianpartridge** [comment]
Thanks for the PR!  We'll get it reviewed soon :)

**Comment by nethraravindran** [comment]
@TheM4hd1 Thanks for the PR! Can we have a test case for this as well?

**Comment by TheM4hd1** [comment]
tests were include a function named ```testGetSelfSignedCert```, which tests ssl, the problem were in the initializing request which fixed with replacing ```.contains``` with ```.hasPrefix```, anyway I've added a test again.
the test url is an insecure url but containing https which could causes error when requesting.
it fixes now.
Regards.

**Comment by nethraravindran** [comment]
@TheM4hd1 can you please look into travis failures?

**Comment by TheM4hd1** [comment]
I'm getting crazy with this travis, thats not my test case error,
mine passed.

```
Test Case '-[SwiftyRequestTests.SwiftyRequestTests testInsecureConnection]' started.
Test Case '-[SwiftyRequestTests.SwiftyRequestTests testInsecureConnection]' passed (0.209 seconds).
```

**Comment by nethraravindran** [comment]
@TheM4hd1 Can you try reproducing this issue on Linux or a docker. It can be a corelibs-foundation bug as well ( I doubt ). Please let me know what you think or if you need some help on this

**Pull request merged**
