### PR TITLE
ci: Update to Swift 4.2.3, use official Docker images

### PR DESCRIPTION
**Pull request by djones6**
Updates the CI to use the latest Swift 4.2.3 release, and the official Swift Docker images.
Using the official Docker images can speed up CI build times as the build does not need manually installing from swift.org, and system dependencies are already set up.

### CODE REVIEW

**Comment by ianpartridge** [comment]
Are we sure it's an expired API key? `testURLTemplateDataCall()` and others use the same key and they seem to be passing.

**Comment by ddunn2** [comment]
@ianpartridge  Yes it's the API key expiring, I checked the response back from the server which stated the key had expired. Neither Dave nor I know why the other tests are still passing but we also don't really know how their API works. 

Either way I don't think it matters as the plan is to remove this external API from our tests and use something we have more control over.

**Comment by ianpartridge** [comment]
OK thanks, it didn't make sense to me that there could be 2 tests using the same API key and only one reports that the key is expired.

What are we going to replace it with?

**Comment by ddunn2** [comment]
It seems that the API key has failed for all the tests, but the tests are only testing failures or they test that the response contains some data. 

In both cases this is true, they fail because there's no API key and there is data in the response: 
```

{
  "response": {
  "version":"0.1",
  "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
  "features": {
  }
		,
	"error": {
		"type": "keynotfound"
		,"description": "this key does not exist"
	}
	}
}
```



As to what we replace it with:
We have two solutions with so far -
1. Use the Kitura Sample application that's currently hosted on IBM cloud. 

2. Have the tests spin up a Kitura server and send the requests at that.

**Pull request merged**
